//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoPoisk.DomainLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinoPoisk.DomainLayer.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for the verification action.
        /// </summary>
        public static string ChechkEmail {
            get {
                return ResourceManager.GetString("ChechkEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t log in, try again later.
        /// </summary>
        public static string CouldntLogIn {
            get {
                return ResourceManager.GetString("CouldntLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s email has already been confirmed.
        /// </summary>
        public static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email.
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email value. The length of the email should not exceed 50 characters.
        /// </summary>
        public static string EmailExceedsMaxLen {
            get {
                return ResourceManager.GetString("EmailExceedsMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email value. The minimum length of the email is 2.
        /// </summary>
        public static string EmailLessMinLen {
            get {
                return ResourceManager.GetString("EmailLessMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s email was not found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account password has been changed.
        /// </summary>
        public static string EmailPasswordChanged {
            get {
                return ResourceManager.GetString("EmailPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register, try again later.
        /// </summary>
        public static string FailedRegister {
            get {
                return ResourceManager.GetString("FailedRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first name value. The length of the user first name should not exceed 50 characters.
        /// </summary>
        public static string FirstNameExceedsMaxLen {
            get {
                return ResourceManager.GetString("FirstNameExceedsMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid first name value. The minimum length of the first name  is 2.
        /// </summary>
        public static string FirstNameLessMinLen {
            get {
                return ResourceManager.GetString("FirstNameLessMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string IdIsRequired {
            get {
                return ResourceManager.GetString("IdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect date of birth value.
        /// </summary>
        public static string IncorrectDateOfBirth {
            get {
                return ResourceManager.GetString("IncorrectDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access or refresh token.
        /// </summary>
        public static string InvalidAccessOrRefreshToken {
            get {
                return ResourceManager.GetString("InvalidAccessOrRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address or password.
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid last name value. The length of the user last name should not exceed 50 characters.
        /// </summary>
        public static string LastNameExceedsMaxLen {
            get {
                return ResourceManager.GetString("LastNameExceedsMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid last name value. The minimum length of the lastname  is 2.
        /// </summary>
        public static string LastNameLessMinLen {
            get {
                return ResourceManager.GetString("LastNameLessMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country with the specified id was not found.
        /// </summary>
        public static string NotFoundUserCountry {
            get {
                return ResourceManager.GetString("NotFoundUserCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null argument.
        /// </summary>
        public static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password value. The length of the password should not exceed 30 characters.
        /// </summary>
        public static string PasswordExceedsMaxLen {
            get {
                return ResourceManager.GetString("PasswordExceedsMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password value. The minimum length of the password is 6.
        /// </summary>
        public static string PasswordLessMinLen {
            get {
                return ResourceManager.GetString("PasswordLessMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered passwords do not match.
        /// </summary>
        public static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patronymic value. The length of the user patronymic should not exceed 50 characters.
        /// </summary>
        public static string PatronymicExceedsMaxLen {
            get {
                return ResourceManager.GetString("PatronymicExceedsMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patronymic value. The minimum length of the patronymic is 2.
        /// </summary>
        public static string PatronymicLessMinLen {
            get {
                return ResourceManager.GetString("PatronymicLessMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string SubjectConfirmEmail {
            get {
                return ResourceManager.GetString("SubjectConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string SubjectPasswordChanged {
            get {
                return ResourceManager.GetString("SubjectPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}!&lt;br&gt;You have been sent this email because you created an account on kinopoisk.&lt;br&gt;Please confirm your account by clicking this link: {1}.
        /// </summary>
        public static string TextConfirmEmail {
            get {
                return ResourceManager.GetString("TextConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}!&lt;br&gt;You have received this email because you have started password recovery. If it wasn&apos;t you, ignore this email.&lt;br&gt;To reset password clicking this link: {1}.
        /// </summary>
        public static string TextResetEmail {
            get {
                return ResourceManager.GetString("TextResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username value. The length of the username should not exceed 50 characters.
        /// </summary>
        public static string UserNameExceedsMaxLen {
            get {
                return ResourceManager.GetString("UserNameExceedsMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username value. The minimum length of the username is 2.
        /// </summary>
        public static string UserNameLessMinLen {
            get {
                return ResourceManager.GetString("UserNameLessMinLen", resourceCulture);
            }
        }
    }
}
